<form method="post" action="<?php echo App::config('url') ?>Index/newPost">

    <div class="form-group">
        <label for="content">What's on your mind?</label>
        <input id="content" name="content" class="form-control">
    </div>

    <button type="submit" class="btn btn-primary">Save</button>

</form>


<?php foreach ($posts as $post): ?>
    <div class="row">
        <div class="col-6">
            <p>
                <a href="<?php echo App::config('url') ?>Index/view/<?= $post->getId() ?> ">
                    <?= htmlspecialchars($post->getContent()) ?>
                </a>
            </p>
        </div>
        <div class="col-6">
            <p><?= date('d.m.Y H:i',strtotime($post->getPostTime())); ?></p>
        </div>
    </div>
<?php endforeach; ?>
