<div class="row">
    <div class="col-4">
        <p><?= htmlspecialchars($post->getContent()) ?></p>
    </div>
    <div class="col-4">
        <p><?= date("d.m.Y H:i",strtotime($post->getPostTime())); ?></p>
    </div>
    <div class="col-4">
        <a href="<?php echo App::config('url') ?>Index/deletePost/<?php echo $post->getId(); ?>" class="btn btn-primary">Delete post</a>
    </div>
</div>

<div class="row">
    <form action="<?php echo App::config('url') ?>Index/newComment" method="post">
        <div class="form-group">
            <label for="content">Comment</label>
            <input type="text" name="content" id="content" class="form-control">
        </div>
        <input type="hidden" name="postid" id="postid" value="<?php echo $post->getId(); ?>">
        <button type="submit" class="btn btn-primary">Send</button>
    </form>
</div>

<div class="row">
    <div class="col-12">
        <h3>Comments</h3>
    </div>
    <div class="col-12">
        <?php foreach ($comments as $comment): ?>
            <p><?= $comment->getContent(); ?></p>
        <?php endforeach; ?>
    </div>
</div>
